/* 
 * The MIT License
 *
 * Copyright 2014 krv.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ossheduleredf;

import com.seaglasslookandfeel.SeaGlassLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP
 */
public class Frame_1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame_1
     */
    public Frame_1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldP_job1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_job1 = new javax.swing.JLabel();
        jTextFieldS_job1 = new javax.swing.JTextField();
        jButtonKill_job1 = new javax.swing.JButton();
        jButtonStart_job1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldP_job2 = new javax.swing.JTextField();
        jTextFieldS_job2 = new javax.swing.JTextField();
        jButtonKill_job2 = new javax.swing.JButton();
        jButtonStart_job2 = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jButtonStart_job4 = new javax.swing.JButton();
        jButtonStart_job3 = new javax.swing.JButton();
        jButtonKill_job3 = new javax.swing.JButton();
        jButtonKill_job4 = new javax.swing.JButton();
        jTextFieldS_job4 = new javax.swing.JTextField();
        jTextFieldS_job3 = new javax.swing.JTextField();
        jTextFieldP_job3 = new javax.swing.JTextField();
        jTextFieldP_job4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldP_job5 = new javax.swing.JTextField();
        jTextFieldP_job6 = new javax.swing.JTextField();
        jTextFieldP_job7 = new javax.swing.JTextField();
        jTextFieldS_job7 = new javax.swing.JTextField();
        jTextFieldS_job5 = new javax.swing.JTextField();
        jTextFieldS_job6 = new javax.swing.JTextField();
        jButtonKill_job6 = new javax.swing.JButton();
        jButtonKill_job5 = new javax.swing.JButton();
        jButtonKill_job7 = new javax.swing.JButton();
        jButtonStart_job7 = new javax.swing.JButton();
        jButtonStart_job6 = new javax.swing.JButton();
        jButtonStart_job5 = new javax.swing.JButton();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jProgressBar7 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldP_job8 = new javax.swing.JTextField();
        jTextFieldP_job9 = new javax.swing.JTextField();
        jTextFieldP_job10 = new javax.swing.JTextField();
        jTextFieldS_job8 = new javax.swing.JTextField();
        jTextFieldS_job9 = new javax.swing.JTextField();
        jTextFieldS_job10 = new javax.swing.JTextField();
        jButtonKill_job10 = new javax.swing.JButton();
        jButtonKill_job9 = new javax.swing.JButton();
        jButtonKill_job8 = new javax.swing.JButton();
        jButtonStart_job8 = new javax.swing.JButton();
        jButtonStart_job9 = new javax.swing.JButton();
        jButtonStart_job10 = new javax.swing.JButton();
        jProgressBar10 = new javax.swing.JProgressBar();
        jProgressBar9 = new javax.swing.JProgressBar();
        jProgressBar8 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldP_job1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP_job1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("JOB #1");

        jLabel_job1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_job1.setText("000.00");

        jTextFieldS_job1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS_job1ActionPerformed(evt);
            }
        });

        jButtonKill_job1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job1.setText("X");
        jButtonKill_job1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job1ActionPerformed(evt);
            }
        });

        jButtonStart_job1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job1.setText("|>");
        jButtonStart_job1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("JOB #2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("000.00");

        jTextFieldP_job2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP_job2ActionPerformed(evt);
            }
        });

        jButtonKill_job2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job2.setText("X");
        jButtonKill_job2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job2ActionPerformed(evt);
            }
        });

        jButtonStart_job2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job2.setText("|>");
        jButtonStart_job2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job2ActionPerformed(evt);
            }
        });

        jButtonStart_job4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job4.setText("|>");
        jButtonStart_job4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job4ActionPerformed(evt);
            }
        });

        jButtonStart_job3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job3.setText("|>");
        jButtonStart_job3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job3ActionPerformed(evt);
            }
        });

        jButtonKill_job3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job3.setText("X");
        jButtonKill_job3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job3ActionPerformed(evt);
            }
        });

        jButtonKill_job4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job4.setText("X");
        jButtonKill_job4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job4ActionPerformed(evt);
            }
        });

        jTextFieldP_job4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP_job4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("000.00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("000.00");

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("JOB #3");

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("JOB #4");

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("JOB #5");

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("JOB #6");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("000.00");

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("JOB #7");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("000.00");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("000.00");

        jTextFieldP_job6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP_job6ActionPerformed(evt);
            }
        });

        jTextFieldS_job7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS_job7ActionPerformed(evt);
            }
        });

        jTextFieldS_job5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS_job5ActionPerformed(evt);
            }
        });

        jButtonKill_job6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job6.setText("X");
        jButtonKill_job6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job6ActionPerformed(evt);
            }
        });

        jButtonKill_job5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job5.setText("X");
        jButtonKill_job5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job5ActionPerformed(evt);
            }
        });

        jButtonKill_job7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job7.setText("X");
        jButtonKill_job7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job7ActionPerformed(evt);
            }
        });

        jButtonStart_job7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job7.setText("|>");
        jButtonStart_job7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job7ActionPerformed(evt);
            }
        });

        jButtonStart_job6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job6.setText("|>");
        jButtonStart_job6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job6ActionPerformed(evt);
            }
        });

        jButtonStart_job5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job5.setText("|>");
        jButtonStart_job5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job5ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("JOB #8");

        jLabel10.setBackground(new java.awt.Color(255, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("JOB #9");

        jLabel11.setBackground(new java.awt.Color(255, 255, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("JOB #10");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("000.00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("000.00");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("000.00");

        jTextFieldP_job8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP_job8ActionPerformed(evt);
            }
        });

        jTextFieldP_job10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP_job10ActionPerformed(evt);
            }
        });

        jTextFieldS_job8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS_job8ActionPerformed(evt);
            }
        });

        jTextFieldS_job9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS_job9ActionPerformed(evt);
            }
        });

        jTextFieldS_job10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS_job10ActionPerformed(evt);
            }
        });

        jButtonKill_job10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job10.setText("X");
        jButtonKill_job10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job10ActionPerformed(evt);
            }
        });

        jButtonKill_job9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job9.setText("X");
        jButtonKill_job9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job9ActionPerformed(evt);
            }
        });

        jButtonKill_job8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKill_job8.setText("X");
        jButtonKill_job8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKill_job8ActionPerformed(evt);
            }
        });

        jButtonStart_job8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job8.setText("|>");
        jButtonStart_job8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job8ActionPerformed(evt);
            }
        });

        jButtonStart_job9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job9.setText("|>");
        jButtonStart_job9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job9ActionPerformed(evt);
            }
        });

        jButtonStart_job10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStart_job10.setText("|>");
        jButtonStart_job10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart_job10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Period");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Service Time");

        jButton1.setText("Run All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job7))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job5))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_job1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldP_job1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldP_job9))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldP_job10))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldS_job1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jTextFieldS_job2)
                            .addComponent(jTextFieldS_job3)
                            .addComponent(jTextFieldS_job4)
                            .addComponent(jTextFieldS_job5)
                            .addComponent(jTextFieldS_job6)
                            .addComponent(jTextFieldS_job7)
                            .addComponent(jTextFieldS_job8)
                            .addComponent(jTextFieldS_job9)
                            .addComponent(jTextFieldS_job10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKill_job10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStart_job10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel21)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel_job1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldP_job1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job1)
                        .addComponent(jButtonStart_job1))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jTextFieldP_job2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job2)
                        .addComponent(jButtonStart_job2))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jTextFieldP_job3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job3)
                        .addComponent(jButtonStart_job3))
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldP_job4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job4)
                        .addComponent(jButtonStart_job4))
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jTextFieldP_job5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job5)
                        .addComponent(jButtonStart_job5))
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jTextFieldP_job6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job6)
                        .addComponent(jButtonStart_job6))
                    .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldP_job7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldS_job7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKill_job7)
                    .addComponent(jButtonStart_job7)
                    .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldP_job8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldS_job8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonKill_job8)
                            .addComponent(jButtonStart_job8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jTextFieldP_job9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldS_job9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonKill_job9)
                                .addComponent(jButtonStart_job9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(jTextFieldP_job10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldS_job10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKill_job10)
                        .addComponent(jButtonStart_job10))
                    .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStart_job10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job10ActionPerformed

    private void jButtonStart_job9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job9ActionPerformed

    private void jButtonStart_job8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job8ActionPerformed

    private void jButtonStart_job7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job7ActionPerformed

    private void jButtonStart_job6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job6ActionPerformed

    private void jButtonStart_job5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job5ActionPerformed

    private void jButtonStart_job4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job4ActionPerformed

    private void jButtonStart_job3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job3ActionPerformed

    private void jButtonStart_job2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStart_job2ActionPerformed

    private void jButtonStart_job1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart_job1ActionPerformed
        int y = 0;
        jProgressBar1.setValue(50);      
    }//GEN-LAST:event_jButtonStart_job1ActionPerformed

    private void jButtonKill_job10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job10ActionPerformed

    private void jButtonKill_job9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job9ActionPerformed

    private void jButtonKill_job8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job8ActionPerformed

    private void jButtonKill_job7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job7ActionPerformed

    private void jButtonKill_job6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job6ActionPerformed

    private void jButtonKill_job5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job5ActionPerformed

    private void jButtonKill_job4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job4ActionPerformed

    private void jButtonKill_job3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job3ActionPerformed

    private void jButtonKill_job2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job2ActionPerformed

    private void jButtonKill_job1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKill_job1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKill_job1ActionPerformed

    private void jTextFieldS_job9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS_job9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS_job9ActionPerformed

    private void jTextFieldS_job8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS_job8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS_job8ActionPerformed

    private void jTextFieldS_job7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS_job7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS_job7ActionPerformed

    private void jTextFieldS_job5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS_job5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS_job5ActionPerformed

    private void jTextFieldS_job1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS_job1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS_job1ActionPerformed

    private void jTextFieldP_job10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP_job10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP_job10ActionPerformed

    private void jTextFieldP_job8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP_job8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP_job8ActionPerformed

    private void jTextFieldP_job6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP_job6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP_job6ActionPerformed

    private void jTextFieldP_job4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP_job4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP_job4ActionPerformed

    private void jTextFieldP_job2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP_job2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP_job2ActionPerformed

    private void jTextFieldP_job1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP_job1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP_job1ActionPerformed

    private void jTextFieldS_job10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS_job10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS_job10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int noOfJobs= 5;
        int deadlineArray[]= new int[noOfJobs];
        int serviceTimeArray[]= new int [noOfJobs];
        
        
        deadlineArray[0]= Integer.parseInt((jTextFieldP_job1.getText().equals(""))?jTextFieldP_job1.getText():"0");
        deadlineArray[1]= Integer.parseInt((jTextFieldP_job2.getText().equals(""))?jTextFieldP_job2.getText():"0");
        deadlineArray[2]= Integer.parseInt((jTextFieldP_job3.getText().equals(""))?jTextFieldP_job3.getText():"0");
        deadlineArray[3]= Integer.parseInt((jTextFieldP_job4.getText().equals(""))?jTextFieldP_job4.getText():"0");
        deadlineArray[4]= Integer.parseInt((jTextFieldP_job5.getText().equals(""))?jTextFieldP_job5.getText():"0");
        
        serviceTimeArray[0]= Integer.parseInt((jTextFieldS_job1.getText().equals(""))?jTextFieldS_job1.getText():"0");
        serviceTimeArray[1]= Integer.parseInt((jTextFieldS_job2.getText().equals(""))?jTextFieldS_job2.getText():"0");
        serviceTimeArray[2]= Integer.parseInt((jTextFieldS_job3.getText().equals(""))?jTextFieldS_job3.getText():"0");
        serviceTimeArray[3]= Integer.parseInt((jTextFieldS_job4.getText().equals(""))?jTextFieldS_job4.getText():"0");
        serviceTimeArray[4]= Integer.parseInt((jTextFieldS_job5.getText().equals(""))?jTextFieldS_job5.getText():"0");
        
        OSShedulerEDF scheduler= new OSShedulerEDF();
        for(int i=0; i<noOfJobs; i++){
            Job j= new Job(deadlineArray[i], serviceTimeArray[i], i);
            scheduler.addNewJob(j);
            System.out.println("new job added to scheduler. period: "+deadlineArray[i]+" service time: "+serviceTimeArray[i]);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            */
            
            // sea glass L&F
            UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
        } catch (Exception ex) {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    } catch (ClassNotFoundException ex1) {
                        Logger.getLogger(Frame_1.class.getName()).log(Level.SEVERE, null, ex1);
                    } catch (InstantiationException ex1) {
                        Logger.getLogger(Frame_1.class.getName()).log(Level.SEVERE, null, ex1);
                    } catch (IllegalAccessException ex1) {
                        Logger.getLogger(Frame_1.class.getName()).log(Level.SEVERE, null, ex1);
                    } catch (UnsupportedLookAndFeelException ex1) {
                        Logger.getLogger(Frame_1.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                    break;
                }
            }
            java.util.logging.Logger.getLogger(Frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonKill_job1;
    private javax.swing.JButton jButtonKill_job10;
    private javax.swing.JButton jButtonKill_job2;
    private javax.swing.JButton jButtonKill_job3;
    private javax.swing.JButton jButtonKill_job4;
    private javax.swing.JButton jButtonKill_job5;
    private javax.swing.JButton jButtonKill_job6;
    private javax.swing.JButton jButtonKill_job7;
    private javax.swing.JButton jButtonKill_job8;
    private javax.swing.JButton jButtonKill_job9;
    private javax.swing.JButton jButtonStart_job1;
    private javax.swing.JButton jButtonStart_job10;
    private javax.swing.JButton jButtonStart_job2;
    private javax.swing.JButton jButtonStart_job3;
    private javax.swing.JButton jButtonStart_job4;
    private javax.swing.JButton jButtonStart_job5;
    private javax.swing.JButton jButtonStart_job6;
    private javax.swing.JButton jButtonStart_job7;
    private javax.swing.JButton jButtonStart_job8;
    private javax.swing.JButton jButtonStart_job9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_job1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JTextField jTextFieldP_job1;
    private javax.swing.JTextField jTextFieldP_job10;
    private javax.swing.JTextField jTextFieldP_job2;
    private javax.swing.JTextField jTextFieldP_job3;
    private javax.swing.JTextField jTextFieldP_job4;
    private javax.swing.JTextField jTextFieldP_job5;
    private javax.swing.JTextField jTextFieldP_job6;
    private javax.swing.JTextField jTextFieldP_job7;
    private javax.swing.JTextField jTextFieldP_job8;
    private javax.swing.JTextField jTextFieldP_job9;
    private javax.swing.JTextField jTextFieldS_job1;
    private javax.swing.JTextField jTextFieldS_job10;
    private javax.swing.JTextField jTextFieldS_job2;
    private javax.swing.JTextField jTextFieldS_job3;
    private javax.swing.JTextField jTextFieldS_job4;
    private javax.swing.JTextField jTextFieldS_job5;
    private javax.swing.JTextField jTextFieldS_job6;
    private javax.swing.JTextField jTextFieldS_job7;
    private javax.swing.JTextField jTextFieldS_job8;
    private javax.swing.JTextField jTextFieldS_job9;
    // End of variables declaration//GEN-END:variables
}
